id = "poimandres-theme"
name = "Poimandres"
version = "0.0.1"
schema_version = 1
authors = ["matiadev <mattcroat.dev@gmail.com>"]
description = "🔥 Poimandres theme with light and blur variations"
repository = "https://github.com/matiadev/poimandres-zed"
